[package]
name = "mc173"
version = "0.1.0"
edition = "2021"
description = "Base data structure and logic for running a Minecraft beta 1.7.3 world"

[dependencies]
crossbeam-channel = "0.5"
byteorder = "1.5"
indexmap = "2.0"
flate2 = "1.0"
glam = "0.24"

thiserror = "1.0"

tracing = "0.1"
